#!/bin/bash

# this script is incomplete, so do not run it.

# install zsh extensions

# adding ppas
sudo add-apt-repository ppa:hvr/ghc # GHC
sudo add-apt-repository ppa:aslatter/ppa # alacritty
sudo add-apt-repository ppa:justinabrahms/ttf-cascadia-code # cascadia code
sudo add-apt-repository ppa:papirus/papirus # Kvantum
sudo add-apt-repository ppa:codejamninja/jam-os # i3lock-color
sudo apt-add-repository ppa:tista/adapta # adapta theme

# for vscode:
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt update

# install stuff
sudo apt install ghc-8.8.4 cabal-install-3.4 compton nitrogen python3-pip alacritty ttf-cascadia-code qt5-style-kvantum qt5-style-kvantum-themes qt5ct pcmanfm-qt papirus-icon-theme fonts-cantarell lxappearance adapta-gtk-theme apt-transport-https xdotool libglib2.0-dev libdbus-1-dev gir1.2-nm-1.0 libnm-util-dev

# installing vscode next (need apt-transport-https installed beforehand)
sudo apt install code

## installing xmonad, xmobar xmonad-contrib
sudo cabal v1-install --global xmobar-0.37 xmonad-0.15 xmonad-contrib-0.16

# install pywal, notify-send.py
sudo pip3 install pywal notify-send.py

# somehow remove everything gnome related and then install lightdm
sudo apt install lightdm

# this will install unity greeter theme, which will reinstall bunch of gnome stuff again, some of which is not required so remove those
sudo apt purge gnome-control-center gnome-bluetooth yelp gnome-terminal

# uninstall xterm if its there
sudo apt purge xterm

# removing orphan packages
sudo apt purge --autoremove

# installing software properties common, if it was removed
sudo apt install software-properties-common

