add_newline = false

# Use custom format
format = "\\[ $directory$git_branch$git_status$python\\]\\$ " 

[git_branch]
symbol = ""

[git_status]
deleted = ""

[python]
format = "[$virtualenv]($style)"
enabled = true
