#!/bin/bash

if [[ "$EUID" -eq 0 ]]; then
    echo "do not run as root"
    exit -1
fi

# installing apps
echo "installing firefox, nitrogen, dunst, light, alsa-utils, ranger, terminator"
sudo pacman -S firefox nitrogen dunst light alsa-utils ranger terminator dzen2 w3m npm
yay -S dunstify
npm install -g rafaelrinaldi/whereami

# installing fonts
yay -S nerd-fonts-complete adobe-source-code-pro-fonts ttf-ms-font ttf-font-awesome

# installing stuff for desktop
echo "installing desktop stuff (rofi, polybar etc)"
sudo pacman -S rofi scrot jsoncpp python-pywal python-setuptools compton
yay -S polybar
echo "(cat ~/.cache/wal/sequences &)" >> .bashrc

# installing themes and lxappearance
echo "installing themes and lxappearance"
sudo pacman -S adapta-gtk-theme papirus-icon-theme lxappearance

# installing miniconda
echo "installing miniconda"
yay -S miniconda3
echo ". /opt/miniconda3/etc/profile.d/conda.sh" >> .bashrc

# installing dotfiles
git clone https://github.com/firekind/dotfiles
cp -a dotfiles/.scripts ~
cp -a dotfiles/.config ~
~/.scripts/change-bg ~/Pictures/Wallpapers/new/mononoke.jpg
i3-msg reload

