#!/bin/bash

if [[ "$EUID" -eq 0 ]]; then
    echo "do not run as root"
    exit -1
fi

# installing xorg
echo "installing xorg stuff"
sudo pacman -S xorg-server xorg-bdftopcf xorg-font-util xorg-font-utils xorg-fonts-encodings xorg-mkfontdir xorg-mkfontscale xorg-server-common xorg-setxkbmap xorg-xkbcomp xorg-xprop xorg-xrandr xorg-xrdb xorg-xset xorgproto

# installing yay
sudo pacman -Q git &> /dev/null
if [[ "$?" != 0 ]]
then
   sudo pacman -S git
fi
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
yay -Sy

# installing display mananger lightdm
sudo pacman -S lightdm
yay -S lightdm-slick-greeter lightdm-settings
sudo systemctl enable lightdm

# installing i3
yay -S i3-gaps i3lock-color rxvt-unicode
echo "NOTE: please edit /etc/lightdm/lightdm.conf greeter-session option to lightdm-slick-greeter
