#!/bin/env sh

launch (){
	pkill polybar
	sleep 1;

	if type "xrandr"; then
	  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		if [[ $1 == "--top" ]]
		then
			MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload top &
		elif [[ $1 == "--bottom-split" ]]
		then
			MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload right &
			MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload left &
		else
			MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload bottom &
		fi
	  done
	else
	  if [[ $1 == "--top" ]]
	  then
		  polybar -c ~/.config/polybar/config.ini --reload top &
	  elif [[ $1 == "--bottom-split" ]]
	  then
		  polybar -c ~/.config/polybar/config.ini --reload right &
		  polybar -c ~/.config/polybar/config.ini --reload left &
	  else
		  polybar -c ~/.config/polybar/config.ini --reload bottom &
	  fi
	fi
}

toggle_hide (){
	xdo_path=$(which xdo)
	if [ $? -ne 0 ]; then
		echo "cannot find \'xdo\' command. " 1>&2
		exit -1
	fi

	id=$(xdo id -N "Polybar")
	
	if xprop -id $id | grep -q "Normal"; then
		xdo hide -N "Polybar"
	else
		xdo show -N "Polybar"
	fi
}


case "$1" in
	-ht)
		toggle_hide
		;;
	-l)
		echo $2
		launch $2
		;;
	*)
		echo "Invalid usage"
		;;
esac
