#!/bin/zsh

source $HOME/.cache/wal/colors.sh

if [[ "$(pgrep -f 'dzen2 -title-name calendar')" ]]
then
   pkill -f "dzen2 -title-name calendar"
   exit 0
fi

ORIG_IFS=$IFS
IFS=" " read current_month current_year <<< $(date +"%m %Y")
IFS=$ORIG_IFS

screen=1

OPTS=`getopt -o m:y:s: -- "$@"`
eval set -- "$OPTS"
# <<<

while true; do
  case "$1" in
    -m ) month="$2"; shift 2 ;;
    -y ) year="$2"; shift 2 ;;
    -s ) screen="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

month=${month:-$current_month}
year=${year:-$current_year}

if (( month > 12)); then
  month=1
  ((year++))
fi

if ((month < 1)); then
  month=12
  ((year--))
fi

#back="^ca(1, calendar -m $((month-1)) -y $year)<^ca()"
#next="^ca(1, calendar -m $((month+1)) -y $year)>^ca()"

#out=$(cal $month $year | sed "1s/^ /$back/; 1s/ $/$next/")
out=$(cal $month $year)
lines=$(echo "$out" | wc -l)
echo "$out"

if test "$month" -eq "$current_month" && test "$year" -eq "$current_year"; then
  out=$(echo "$out" | sed -e "2,/$(date +%e)/ s/\($(date +%e)\)/^fg($color0)^bg($color7)\1^fg()^bg()/")
fi

echo  "$out" | dzen2 \
  -title-name "calendar" \
  -bg "$color0" \
  -fg "$color7" \
  -x 835 \
  -y 45 \
  -h 35 \
  -l $((lines-1)) \
  -w 250 \
  -fn "Source Code Pro" \
  -e "onstart=uncollapse;entertitle=grabkeys;enterslave=grabkeys;leaveslave=ungrabkeys;button3=exit;key_Escape=exit,ungrabkeys" \
  -ta c \
  -sa c \
  -xs $screen \
  -p &
echo "$out"
