#!/bin/bash

if [[ "$EUID" -eq 0 ]]; then
    echo "do not run as root"
    exit -1
fi

PP="firefox
nitrogen
dunst
light
alsa-utils
ranger
terminator
dzen2
w3m
stow
npm
rofi
scrot
jsoncpp
python-pywal
python-setuptools
compton
adapta-gtk-theme
papirus-icon-theme
lxappearance"

PY="nerd-fonts-complete
adobe-source-code-pro-fonts
ttf-ms-font
ttf-font-awesome
polybar
miniconda3
redshift-minimal"

SL="dunst
i3
polybar
rofi
scripts
terminator
vim
wal
zsh"

# installing apps
echo " ==> installing(via pacman): $(echo $PP | sed 's/\n/, /g')"
sudo pacman -S $PP

echo -e "\n ==> installing(via yay): $(echo $PY | sed 's/\n/, /g')"
yay -S $PY

echo -e "\n ==> installing(via npm): whereami"
npm install -g rafaelrinaldi/whereami

# installing dotfiles
echo -e "\n ==> installing: dotfiles"
git clone https://github.com/firekind/dotfiles ~/Dotfiles
cd Dotfiles
stow $SL
~/.scripts/change-bg ~/Dotfiles/desktop-setup-stuff/Wallpaper/tallneck.jpg
i3-msg reload

