#!/bin/bash

if [[ "$EUID" -eq 0 ]]; then
    echo "do not run as root"
    exit -1
fi

PP="xorg-server
xorg-bdftopcf
xorg-font-utils
xorg-fonts-encodings
xorg-mkfontdir
xorg-mkfontscale
xorg-server-common
xorg-setxkbmap
xorg-xkbcomp
xorg-xprop
xorg-xrandr
xorg-xrdb
xorg-xset
xorgproto
xclip
git
lightdm"

PY="lightdm-slick-greeter
lightdm-settings
i3-gaps
i3lock-color
rxvt-unicode"

# installing xorg
echo -e " ==> installing(via pacman): $(echo $PP | sed 's/\n/, /g')"
sudo pacman -S $PP

# installing yay
echo -e "\n ==> installing: yay"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
sudo rm -r yay
yay -Sy

echo -e "\n ==> installing(via yay): $(echo $PY | sed 's/\n/, /g')"
yay -S $PY

echo -e "\n ==> info: enabling lightdm"
sudo systemctl enable lightdm

echo -e "\n ==> IMPORTANT: set greeter-session option to lightdm-slick-greeter in /etc/lightdm/lightdm.conf" 
