#!/bin/bash
if [ "$1" == "-r" ]
then
	xrandr --output HDMI-1-1 --auto --mode 1920x1080 --right-of eDP-1-1
elif [ "$1" == "-e" ]
then
	xrandr --output eDP-1-1 --off --output HDMI-1-1 --auto --mode 1920x1080
elif [ "$1" == "-s" ]
then
	xrandr --output HDMI-1-1 --off --output eDP-1-1 --auto
elif [ "$1" == "-l" ]
then
	xrandr --output HDMI-1-1 --auto --mode 1920x1080 --left-of eDP-1-1
else
	echo "usage: change-monitor [-r | -l | -e | -s]"
	exit
fi
~/.config/polybar/scripts/launch.sh
