#!/bin/bash

# script converts the zip files (which were epubs) to azw3 files after compressing the images 
# present in the original epub 

mkdir res

for file in *.zip; do
	mkdir tmp
	printf "unziping $file...\n"
	unzip "$file" -d tmp &> /dev/null

	printf "compressing...\n"
	cd tmp/OEBPS/images
	for img in *.jpg; do
		convert -strip -interlace Plane -sampling-factor 4:2:0 -define jpeg:dct-method=float -resize x720 -quality 85% "$img" "$img" &> /dev/null
	done

	printf "creating azw3 file...\n"

	cd ../../
	zip -r "$file" META-INF mimetype OEBPS &> /dev/null
	mv "$file" "../res/$(basename "$file" .zip).epub"
	
	cd ../res
	ebook-convert "$(basename "$file" .zip).epub" "$(basename "$file" .zip).azw3" &> /dev/null
	rm "$(basename "$file" .zip).epub"

	cd ..
	rm -r tmp

	printf "done.\n\n"
done
	

