#!/bin/bash
. /opt/miniconda3/etc/profile.d/conda.sh

cd ~
conda activate jupyter
jupyter notebook --no-browser &
google-chrome-stable --app=http://localhost:8888 --user-data-dir=/tmp &> /dev/null
kill $(pgrep -f jupyter)
echo "done"
