#!/bin/bash

case "$1" in
    inc)
        light -A 10
        ;;
    dec)
        light -U 10
        ;;
    *)
        echo "Usage: brightness {inc, dec}"
esac

TEXT=$(light -G | cut -d '.' -f 1)
notify-send.py "Brightness: $TEXT%" -r 10


# if the brightness doesnt change, try adding the user to group 'video'. If
# that does not work, add the following udev rules (replacing <vendor> with the folder name in /sys/class/backlight) 
# to /etc/udev/rules.d/50-brightness.rules to allow users of group 'video' to change brightness (by default, only root can 
# change brightness):

# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="<vendor>", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="<vendor>", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

# then add the user to the group video
# usermod -aG video <user>
