#!/bin/bash

DATE=$(date '+%-Y-%0m-%_d|%a, %0d %b %0H:%0M|%B')
DAY_NUM=${DATE:8:2}

cal_command() {
    cal | sed '1d;s/ *$//g;/^$/d'
}

counts_cal_lines() {
    LINES=$(cal_command | wc -l)
}

FORMATTED_DATE="${DATE:11:7} ${DATE:29}"
counts_cal_lines

cal_command | \
    sed "s#\b${DAY_NUM// /}\b#<span bgcolor='\#ffffff' color='\#000000'>${DAY_NUM// /}</span>#" \
    | rofi \
        -dmenu \
        -width '-22' \
        -lines "$LINES" \
        -theme themes/info.rasi \
        -p "$FORMATTED_DATE" \
        -a '0' \
        -no-custom \
        -markup-rows &> /dev/null
