#!/bin/bash

# generating color scheme using pywal
if [[ "$1" == "" ]]
then
   wal -i ~/Pictures/Wallpapers -n
else
   wal -i $1 -n
fi

# setting wallpaper
if xhost &> /dev/null
then
    # set and save wallpaper
    feh --bg-fill $(cat ~/.cache/wal/wal)
else
    echo "Display server is not available or is invalid. Not setting wallpaper."
fi

# update Xresouces
cp ~/.cache/wal/colors.Xresources ~/.Xresources

# reload Xresouces
xrdb ~/.Xresources

# kill any instances of dunst and restart it
pkill dunst
dunst &> /dev/null &

