#!/bin/bash

if [[ "$1" != "off" ]]; then
    xrandr --output eDP-1-1 --auto
    xrandr --output HDMI-0 --auto --right-of eDP-1-1 --primary
    nitrogen --restore && picom -b
else
    xrandr --output HDMI-0 --off --output eDP-1-1 --primary
fi

