#!/bin/sh

insideCircleColor='#00000000'  # blank
D='#ffffffff'  # default
Hl='#00ff00ff'  
textColor='#ffffffff'
#W='#880000bb'  # wrong
W='#ff0000ff'
i3lock \
    --blur 1 \
    --insidever-color=$insideCircleColor   \
    --ringver-color=$Hl     \
    --insidewrong-color=$insideCircleColor \
    --ringwrong-color=$W   \
    --inside-color=$insideCircleColor      \
    --ring-color=$textColor        \
    --line-color=$insideCircleColor        \
    --separator-color=$insideCircleColor   \
    --verif-color=$textColor        \
    --wrong-color=$textColor \
    --verif-text="" \
    --wrong-text=""

