#!/bin/sh

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

case "$1" in
   lock)
       ~/.config/custom-scripts/lock -b
       ;;
   logout)
       i3-msg exit
       ;;
   switch_user)
       dm-tool switch-to-greeter
       ;;
   suspend)
       ~/.config/custom-scripts/lock -b && $logind suspend
       ;;
   hibernate)
       ~/.config/custom-scripts/lock -b && $logind hibernate
       ;;
   reboot)
       $logind reboot
       ;;
   shutdown)
       $logind poweroff
       ;;
   *)
       echo "== ! i3exit: missing or invalid argument ! =="
       echo "Try again with :lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
       exit 2
esac
exit 0

