#!/bin/bash

case "$1" in
    decrease)
     	amixer -q set Master 3%- unmute
 	    TEXT=$(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)%
        ;;

    increase)
     	amixer -q set Master 3%+ unmute
 	    TEXT=$(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)%
        ;;

    mute)
 	    amixer -q set Master toggle
 	    TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f8 | sed 's/\(\[\|\]\)//g')
        ;;

    *)
     	echo "Error. Usage: volume {decrease, increase, mute}"
        exit -1
        ;;
esac

dunstify "Volume: $TEXT" -r -20

